openapi: 3.0.3
info:
  title: DDD Demo Gateway - OpenAPI 3.0
  description: |-
    DDD Demo Gateway API for testing.
  termsOfService: https://github.com/dennisholee
  contact:
    email: dennisholee@gmail.com
  license:
    name: Apache 2.0
    url: https://github.com/dennisholee
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: https://github.com/dennisholee
servers:
  - url: http://localhost:8081/api
    description: Development server
  - url: https://localhost:8081/api
    description: Development server with TLS Profile
tags:
  - name: Email
    description: Email notification
    externalDocs:
      description: Find out more
      url: http://swagger.io
      
paths:
  /email:
    post:
      tags:
        - Email
      summary: Send email
      description: Send email
      operationId: sendEmail
      requestBody:
        description: Send email
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailNotification'
          application/xml:
            schema:
              $ref: '#/components/schemas/EmailNotification'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EmailNotification'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailNotification'          
            application/xml:
              schema:
                $ref: '#/components/schemas/EmailNotification'
        '405':
          description: Invalid input
      security:
        - bearerAuth:
            - write:customer
            - read:customer

components:
  schemas:
    EmailNotification:
      type: object
      properties:
        to:
          type: string
          format: email
          minLength: 3
          maxLength: 100
          example: "john.doe@email.com"
        subject:
          type: string
          maxLength: 100
          example: "Greetings from John"
        body:
          type: string
          maxLength: 1000
          example: Hi Paul, Nice to meet you.
          
  securitySchemes:
    bearerAuth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:customer: modify customer
            read:customer: read customer
    api_key:
      type: apiKey
      name: api_key
      in: header