openapi: 3.0.0
info:
  title: Pet Store API
  version: 1.0.0
  description: A simple pet store API example
servers:
  - url: https://api.petstore.example.com/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetsResponse'
    post:
      summary: Create a pet
      operationId: createPet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetRequest'
      responses:
        '201':
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    PetRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        tag:
          type: string
    PetsResponse:
      type: object
      required:
        - pets
      properties:
        pets:
          type: array
          items:
            $ref: '#/components/schemas/Pet'

