@startuml

Title Search Policy

component [Service Consumer] as SC << XAPI >>
component [Individual Life] as IL << PAPI >>
component [Corporate Solution] as CS << PAPI >>
component [Pension] as PT << PAPI >>
component [Vitality] as VT << PAPI >>

component [Client Module] as CM << Component >>
component [EBenefit] as EB << Component >>
component [Vitality Admin Server (VAS)] as VAS << Component >>
component [Pension BE] as PTBE << Component >>

component CM {
  port AlphaSearch
  port FindPolicy
}

interface FindPolicyIF as PII1
interface FindPolicyIF as PII2
interface FindPolicyIF as PII3
interface FindPolicyIF as PII4

 
SC .d.> PII1
SC .d.> PII2
SC .d.> PII3
SC .d.> PII4

PII1 -d- IL
PII2 -d- CS
PII3 -d- PT
PII4 -d- VT

IL .d.> AlphaSearch
IL .d.> FindPolicy

CS .d.> EB

VT .d.> VAS

PT .d.> PTBE



@enduml