@startuml
Component [Mobile] as MOB
Component [Web Portal] as WEB
[Registration BFF] <<XAPI>> as RBFF
[Identity and Access] <<PAPI>> as IDA
[User Profile] <<PAPI>> as User
[Communication Hub] <<SAPI>> as CHUB
[Twillio] <<SMS Gateway>> as TWL
[EMMA] <<SMS Gateway>> as EM
[IAM Gateway] <<SAPI>> as IAMG
[CIAM] <<Component>> as CIAM
[ADB2C] <<SaaS>> as ADB2C

interface Registration as RegIF
interface CreateUser as IAMCreateUserIF
interface OnboardUser as OBUserIF
interface CreateCredential as CredIF
interface SendSMS as SmsIF
interface SendOTP as OtpIF
interface CreateUser as CreateUserIF

MOB ..> RegIF
WEB ..> RegIF

RegIF -d- RBFF

RBFF ..> OBUserIF
OBUserIF -d- User



RBFF ..> CredIF
RBFF ..> OtpIF
CredIF -d- IDA
OtpIF -d- IDA


IDA ..> SmsIF
SmsIF -d- CHUB

IDA ..> IAMCreateUserIF
IAMCreateUserIF -d- IAMG

IAMG ..> CreateUserIF
CreateUserIF -d- CIAM
CIAM -d- ADB2C


CHUB -d- TWL
CHUB -d- EM
@enduml